import FWCore.ParameterSet.Config as cms
import FWCore.Utilities.FileUtils as FileUtils

process = cms.Process("Test")

#readFiles = cms.untracked.vstring( FileUtils.loadListFromFile ('patZjetsfiles.txt') )

process.source = cms.Source("PoolSource",
  fileNames = cms.untracked.vstring(
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_1.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_2.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_3.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_4.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_5.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_6.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_7.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_8.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_9.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_10.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_11.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_12.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_13.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_14.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_15.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_16.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_17.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_18.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_19.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_20.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_21.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_22.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_23.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_24.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_25.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_26.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_27.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_28.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_29.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_30.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_31.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_32.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_33.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_34.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_35.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_36.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_37.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_38.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_39.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_40.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_41.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_42.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_43.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_44.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_45.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_46.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_47.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_48.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_49.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_50.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_51.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_52.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_53.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_54.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_55.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_56.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_57.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_58.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_59.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_60.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_61.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_62.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_63.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_64.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_65.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_66.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_67.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_68.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_69.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_70.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_71.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_72.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_73.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_74.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_75.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_76.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_77.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_78.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_79.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_80.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_81.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_82.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_83.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_84.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_85.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_86.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_87.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_88.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_89.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_90.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_91.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_92.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_93.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_94.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_95.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_96.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_97.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_98.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_99.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_100.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_101.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_102.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_103.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_104.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_105.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_106.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_107.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_108.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_109.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_110.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_111.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_112.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_113.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_114.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_115.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_116.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_117.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_118.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_119.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_120.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_121.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_122.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_123.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_124.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_125.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_126.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_127.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_128.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_129.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_130.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_131.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_132.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_133.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_134.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_135.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_136.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_137.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_138.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_139.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_140.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_141.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_142.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_143.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_144.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_145.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_146.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_147.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_148.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_149.root",
"rfio:/castor/cern.ch/user/k/kreis/diboson/ZZ/ZZ_myPAT_CRAB_all_cor_150.root",
  )
#  fileNames = readFiles
)

process.MessageLogger = cms.Service("MessageLogger")

process.analyzeBasicPat = cms.EDFilter("DistributionAnalyzer",
  photonSrc   = cms.untracked.InputTag("cleanLayer1Photons"),
  electronSrc = cms.untracked.InputTag("cleanLayer1Electrons"),
  muonSrc     = cms.untracked.InputTag("cleanLayer1Muons"),                                             
  tauSrc      = cms.untracked.InputTag("cleanLayer1Taus"),
  jetSrc      = cms.untracked.InputTag("cleanLayer1Jets"),
  metSrc      = cms.untracked.InputTag("layer1METs")
)

process.TFileService = cms.Service("TFileService",
                                   fileName = cms.string('plotsOfPAT_ZZ.root')
                                   )

process.p = cms.Path(process.analyzeBasicPat)

