rfcp /castor/cern.ch/user/k/kreis/CUSusy/RA2/ABCD/trees/T_TagFraction_QCD_Pt15.root /cu1/kreis/QCD/T_TagFraction_QCD_Pt15.root
rfcp /castor/cern.ch/user/k/kreis/CUSusy/RA2/ABCD/trees/T_TagFraction_QCD_Pt30.root /cu1/kreis/QCD/T_TagFraction_QCD_Pt30.root
rfcp /castor/cern.ch/user/k/kreis/CUSusy/RA2/ABCD/trees/T_TagFraction_QCD_Pt80.root /cu1/kreis/QCD/T_TagFraction_QCD_Pt80.root
rfcp /castor/cern.ch/user/k/kreis/CUSusy/RA2/ABCD/trees/T_TagFraction_QCD_Pt170.root /cu1/kreis/QCD/T_TagFraction_QCD_Pt170.root
rfcp /castor/cern.ch/user/k/kreis/CUSusy/RA2/ABCD/trees/T_TagFraction_QCD_Pt170_2.root /cu1/kreis/QCD/T_TagFraction_QCD_Pt170_2.root
rfcp /castor/cern.ch/user/k/kreis/CUSusy/RA2/ABCD/trees/T_TagFraction_QCD_Pt300.root /cu1/kreis/QCD/T_TagFraction_QCD_Pt300.root
rfcp /castor/cern.ch/user/k/kreis/CUSusy/RA2/ABCD/trees/T_TagFraction_QCD_Pt300_2.root /cu1/kreis/QCD/T_TagFraction_QCD_Pt300_2.root
rfcp /castor/cern.ch/user/k/kreis/CUSusy/RA2/ABCD/trees/T_TagFraction_QCD_Pt470.root /cu1/kreis/QCD/T_TagFraction_QCD_Pt470.root
rfcp /castor/cern.ch/user/k/kreis/CUSusy/RA2/ABCD/trees/T_TagFraction_QCD_Pt470_2.root /cu1/kreis/QCD/T_TagFraction_QCD_Pt470_2.root
rfcp /castor/cern.ch/user/k/kreis/CUSusy/RA2/ABCD/trees/T_TagFraction_QCD_Pt800.root /cu1/kreis/QCD/T_TagFraction_QCD_Pt800.root
rfcp /castor/cern.ch/user/k/kreis/CUSusy/RA2/ABCD/trees/T_TagFraction_QCD_Pt1400.root /cu1/kreis/QCD/T_TagFraction_QCD_Pt800_2.root
