rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_1.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_2.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_3.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_4.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_5.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_6.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_7.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_8.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_9.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_10.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_11.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_12.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_13.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_14.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_15.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_16.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_17.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_18.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_19.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_20.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_21.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_22.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_23.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_24.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_25.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_26.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_27.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_28.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_29.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_30.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_31.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_32.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_33.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_34.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_35.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_36.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_37.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_38.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_39.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_40.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_41.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_42.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_43.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_44.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_45.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_46.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_47.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_48.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_49.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_50.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_51.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_52.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_53.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_54.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_55.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_56.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_57.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_58.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_59.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_60.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_61.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_62.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_63.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_64.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_65.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_66.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_67.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_68.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_69.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_70.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_71.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_72.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_73.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_74.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_75.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_76.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_77.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_78.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_79.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_80.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_81.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_82.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_83.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_84.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_85.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_86.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_87.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_88.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_89.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_90.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_91.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_92.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_93.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_94.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_95.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_96.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_97.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_98.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_99.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_100.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_101.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_102.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_103.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_104.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_105.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_106.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_107.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_108.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_109.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_110.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_111.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_112.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_113.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_114.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_115.root
rfrm /castor/cern.ch/user/k/kreis/myPAT_CRAB_all_cor_116.root
